// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX76GzjqonGRTYUwukNY2a8hPs3ivzUPE',
    appId: '1:618735219288:web:b21b3ee481827d086a102d',
    messagingSenderId: '618735219288',
    projectId: 'pi3-t01-07-bateaqui',
    authDomain: 'pi3-t01-07-bateaqui.firebaseapp.com',
    storageBucket: 'pi3-t01-07-bateaqui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAocjMxonme6UNVTeGzRzeD2qjhuiaENcw',
    appId: '1:618735219288:android:51d7b0cb686113026a102d',
    messagingSenderId: '618735219288',
    projectId: 'pi3-t01-07-bateaqui',
    storageBucket: 'pi3-t01-07-bateaqui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_GDypOJZY1ntM6EUxbq8AmzexXGF0YA0',
    appId: '1:618735219288:ios:501774213cd9b5f46a102d',
    messagingSenderId: '618735219288',
    projectId: 'pi3-t01-07-bateaqui',
    storageBucket: 'pi3-t01-07-bateaqui.appspot.com',
    iosBundleId: 'com.projetointegrador.bateaquiAdm',
  );
}
